//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMVersion1._0
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public long Id { get; set; }
        public string Name { get; set; }
        public string Adress { get; set; }
        public string Telefon { get; set; }
        public string Website { get; set; }
        public string FileName { get; set; }
        public byte[] Data { get; set; }
    }
}
