//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMVersion1._0
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public long Id { get; set; }
        public long Item1 { get; set; }
        public decimal Quantity { get; set; }
        public long InvoiceID { get; set; }
        public long ServiceID { get; set; }
    
        public virtual Invoice Invoice { get; set; }
        public virtual Service Service { get; set; }
    }
}
